server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LeilaLandrichix/pbads-microservices.git
          search-paths: pbads-microservices/config-repo
          default-label: main
          clone-on-start: true
          force-pull: true
          timeout: 10

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

